### ISSUE TITLE
Support bracketed paste mode escape sequences

### ISSUE THREAD

**Issue by tdryer** [wardi/urwid#119]
I'm trying to use [bracketed paste mode](https://cirw.in/blog/bracketed-paste) so my application can detect when the user is pasting text. With this mode enabled, the terminal will wrap pasted text with two escape sequences. I've written code to enable bracketed paste mode, but currently urwid seems to be unable to receive the escape sequences when text is pasted.

**Comment by tdryer** [comment]
urwid can actually receive the escape sequences just fine. I was using a version of gnome-terminal with [a bug that causes bracketed paste mode to be enabled per-screen rather than per-terminal](https://bugzilla.gnome.org/show_bug.cgi?id=729533). The solution is to enable bracketed paste mode after urwid has changed to the alternate screen (after `urwid.MainLoop.start`).

**Comment by exquo** [comment]
@tdryer, would you consider making a pull request to urwid of your implementation of the bracketed paste mode?

**Comment by tdryer** [comment]
I don't have a full implementation, but I got it working for an edit widget:

* [enable bracketed paste mode](https://github.com/tdryer/hangups/blob/8874aafc8f7fa90b7f8308a4f61f7ef1b4cd7254/hangups/ui/__main__.py#L1052-L1059)
* [interpret begin/end paste key codes](https://github.com/tdryer/hangups/blob/8874aafc8f7fa90b7f8308a4f61f7ef1b4cd7254/hangups/ui/__main__.py#L468-L481)

**Comment by exquo** [comment]
Thank you very much for pointers to the code! 

Now I see that you have *already* contributed to urwid the "Add bracketed paste mode escape sequences": 4406521b55ca97a07cde748ddc02548e62141eb0	👏

So, bracketed paste mode can already be used with urwid pretty easily, like is done in hangups. 

For what remains to get it to a full implementation:

- Bracketed paste mode needs to be enabled before starting urwid loop and disabled afterwards (sending the `\e[?2004h` and `\e[?2004l` codes). Do you think there are any reasons for urwid not to do this by default? Was it omitted originally in your commit because of the bug in `libvte` that you've referenced?

- Support for widgets other then `urwid.Edit`
	
	I think it's currently the only widget that is relevant for pasting text into. But in any case, urwid could have a `paste_mode_on` boolean available to any widget that is interested in checking it at runtime (e.g. on getting the `enter` keypress event).

Is there anything else?

Seems like most of the work is done already. If all it needs is a final push, I'd like to make this more readily available.

**Comment by tdryer** [comment]
> Do you think there are any reasons for urwid not to do this by default? Was it omitted originally in your commit because of the bug in `libvte` that you've referenced?

No. I think I just did enough in urwid to get the rest working in hangups.

**Comment by exquo** [comment]
Makes sense. I now got it working for my current purposes. When I have the time I'll see what needs to be done to merge the rest into urwid proper.

Thanks again!
